#SPDX-License-Identifier: MIT-0
---
# tasks file for base
- name: Update locale
  ansible.builtin.command: locale-gen {{ locale }}
  become: true

- name: Update timezone
  ansible.builtin.command: timedatectl set-timezone {{ timezone }}
  become: true

- name: Update all packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  become: true

- name: Check if reboot is required
  ansible.builtin.command: test -f /var/run/reboot-required
  register: reboot_required
  ignore_errors: true

- name: Reboot if required
  ansible.builtin.reboot:
    msg: "Rebooting to apply updates"
  when: reboot_required.rc == 0
  become: true