[project]
name = "terraform"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ansible>=11.8.0",
    "boto3>=1.40.0",
    "dynaconf>=3.2.11",
    "python-dotenv>=1.1.1",
    "python-openstackclient>=8.1.0",
    "textual>=5.1.1",
]
