#SPDX-License-Identifier: MIT-0
---
# tasks file for caddy

- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - curl
      - debian-archive-keyring
      - debian-keyring

    state: present
  become: true

- name: Add Caddy GPG key
  ansible.builtin.apt_key:
    url: https://dl.cloudsmith.io/public/caddy/stable/gpg.key
    state: present
  become: true

- name: Add Caddy repository
  ansible.builtin.apt_repository:
    repo: "deb [trusted=yes] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main"
    state: present
  become: true

- name: Install Caddy
  ansible.builtin.apt:
    name: caddy
    state: present
  become: true

- name: Ensure Caddy service is enabled and started
  ansible.builtin.systemd:
    name: caddy
    enabled: true
    state: started
  become: true