#SPDX-License-Identifier: MIT-0
---
# tasks file for minio

- name: Update locale
  ansible.builtin.command: locale-gen {{ locale }}
  become: true

- name: Update timezone
  ansible.builtin.command: timedatectl set-timezone {{ timezone }}
  become: true

- name: Update all packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
  become: true

- name: Check if reboot is required
  ansible.builtin.command: test -f /var/run/reboot-required
  register: reboot_required
  ignore_errors: true

- name: Reboot if required
  ansible.builtin.reboot:
    msg: "Rebooting to apply updates"
  when: reboot_required.rc == 0
  become: true

- name: Download MinIO .deb
  ansible.builtin.get_url:
#      url: https://dl.min.io/server/minio/release/linux-amd64/minio_{{ minio_version }}.deb
      url: https://dl.min.io/server/minio/release/linux-amd64/archive/minio_{{ minio_version }}.deb
      checksum: "{{ minio_checksum }}"
      dest: /tmp/minio.deb

- name: Install MinIO .deb
  ansible.builtin.apt:
    deb: /tmp/minio.deb
    state: present
  become: true

- name: create MinIO group
  ansible.builtin.group:
      name: minio-user
      state: present
  become: true

- name: create MinIO user
  ansible.builtin.user:
    name: minio-user
    group: minio-user
    shell: /sbin/nologin
    system: true
  become: true

- name: Ensure minio user/group owns the MinIO directories
  ansible.builtin.file:
    path: "/mnt/{{ item.value.label }}"
    owner: minio-user
    group: minio-user
    state: directory
    mode: '0750'
  become: true
  loop: "{{ volumes | dict2items }}"

- name: Create environment file for MinIO
  tags: minio_env_file
  ansible.builtin.template:
    src: minio.env.j2
    dest: /etc/default/minio
    mode: '0640'
    owner: root
    group: minio-user
  become: true

- name: Stop and disable apparmor
  tags: disable_apparmor
  ansible.builtin.systemd:
    name: apparmor
    enabled: false
    state: stopped
  become: true

- name: Enable and start MinIO service
  ansible.builtin.systemd:
    name: minio
    enabled: true
    state: started
  become: true

